#!/bin/sh
mount -o ro -t ext4 /dev/sda1 /boot

exec kexec \
	-l \
	--module "/boot/vmlinuz-4.1.13-9.pvops.qubes.x86_64 placeholder root=/dev/mapper/qubes_dom0-root ro i915.preliminary_hw_support=1 rd.lvm.lv=qubes_dom0/root rd.luks.uuid=luks-0f662ac6-2939-48fe-bc95-f5a7e3d6fefb vconsole.font=latarcyrheb-sun16 rd.lvm.lv=qubes_dom0/swap rhgb" \
	--module "/boot/initramfs-4.1.13-9.pvops.qubes.x86_64.img" \
	--command-line "console=vga dom0_mem=min:1024M dom0_mem=max:4096M" \
	/boot/xen-4.6.3.gz
