#!/bin/sh
# Bring up the x230's NIC, get a DHCP address, and invoke keylime

. /etc/functions

insmod /lib/modules/e1000e.ko
udhcpc -n

cd /
wget-measure.sh 6 http://keylime-server/keylime.tar.gz
tar -xvzf keylime.tar.gz

if [ ! -x /keylime_node ]; then
  recovery 'Keylime overlay not found?'
fi

/keylime_node &
KEYLIME_PID=$!

wait $KEYLIME_PID
recovery 'Keylime-node failed unexpectedly'
