#!/bin/sh
# extend a TPM PCR with a module and then load it
# any arguments will also be measured.
# The default PCR to be extended is 5, but can be
# overridden with the MODULE_PCR environment variable

die() {
        echo >&2 "$@"
        exit 1
}

MODULE="$1"; shift

if [ -z "$MODULE_PCR" ]; then
	MODULE_PCR=5
fi

if [ -z "$MODULE" ]; then
	die "Usage: $0 module [args...]"
fi

if [ ! -r "$MODULE" ]; then
	die "$MODULE: not found?"
fi

tpmx extend "$MODULE" "$MODULE_PCR" || die "$MODULE: tpm extend failed"

if [ ! -z "$*" ]; then
	TMPFILE=/tmp/insmod.$$
	echo "$@" > $TMPFILE
	tpmx extend $TMPFILE "$MODULE_PCR" \
	|| die "$MODULE: tpm extend on arguments failed"
fi

# Since we have replaced the real insmod, we must invoke
# the busybox insmod via the original executable
busybox insmod "$MODULE" "$@" \
|| die "$MODULE: insmod failed"
